"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  UploadCloud,
  X,
  Package,
  CheckCircle2,
  AlertCircle,
  Sparkles,
} from "lucide-react";
import { Category } from "@/lib/types";
import { supabase } from "@/lib/supabase";
import { uploadProductImage } from "@/lib/storage";
import { getLiveCategories } from "@/lib/categories";
import { saveProduct } from "@/lib/customProducts";

export default function NewProductPage() {
  const router = useRouter();

  // Categories list
  const [categories, setCategories] = useState<Category[]>([]);
  const [loadingCategories, setLoadingCategories] = useState(true);

  // Form Fields
  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [sku, setSku] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [price, setPrice] = useState("");
  const [technicianPrice, setTechnicianPrice] = useState("");
  const [retailPrice, setRetailPrice] = useState("");
  const [purchasePrice, setPurchasePrice] = useState("");
  const [stockQuantity, setStockQuantity] = useState("25");
  const [minOrderQuantity, setMinOrderQuantity] = useState("1");
  const [shortDescription, setShortDescription] = useState("");
  const [description, setDescription] = useState("");
  const [isActive, setIsActive] = useState(true);
  const [isFeatured, setIsFeatured] = useState(false);
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);

  // Image Upload State
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);

  // Status & Validation
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [successToast, setSuccessToast] = useState(false);

  // Load Categories on mount
  useEffect(() => {
    async function loadCats() {
      setLoadingCategories(true);
      try {
        const liveCats = await getLiveCategories();
        if (liveCats && liveCats.length > 0) {
          setCategories(liveCats as Category[]);
          setCategoryId(liveCats[0].id);
        } else {
          // Fallback defaults
          const fallbackCats: Category[] = [
            { id: "cat-1", name: "LCD & Touch Units", slug: "lcd-units" },
            { id: "cat-2", name: "Charging Flex & Boards", slug: "charging-flex" },
            { id: "cat-3", name: "OCA Glass & Lens", slug: "oca-glass" },
            { id: "cat-4", name: "Batteries & Housings", slug: "batteries-housings" },
            { id: "cat-5", name: "Repair Tools & Supplies", slug: "repair-tools" },
          ];
          setCategories(fallbackCats);
          setCategoryId(fallbackCats[0].id);
        }
      } catch {
        // Handled silently
      } finally {
        setLoadingCategories(false);
      }
    }

    loadCats();
  }, []);

  const generateSlug = (text: string) => {
    return text
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setName(val);
    if (slugAutoGenerated) {
      setSlug(generateSlug(val));
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith("image/")) {
      setFormError("Please select a valid image file (JPG, PNG, WEBP).");
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      setFormError("File size exceeds 5MB limit.");
      return;
    }

    setFormError(null);
    setSelectedFile(file);
    setImagePreview(URL.createObjectURL(file));
  };

  const handleRemoveImage = () => {
    setSelectedFile(null);
    if (imagePreview) {
      URL.revokeObjectURL(imagePreview);
    }
    setImagePreview(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    // Validation
    if (!name.trim() || !sku.trim() || !price || !stockQuantity) {
      setFormError("Please fill all required fields (Name, SKU, Wholesale Price, and Stock).");
      return;
    }

    const numPrice = parseFloat(price);
    const numStock = parseInt(stockQuantity, 10);

    if (isNaN(numPrice) || numPrice < 0) {
      setFormError("Wholesale Selling Price must be a valid non-negative number.");
      return;
    }

    if (isNaN(numStock) || numStock < 0) {
      setFormError("Stock Quantity must be a valid positive integer.");
      return;
    }

    let numTechnicianPrice: number | null = null;
    if (technicianPrice && technicianPrice.trim() !== "") {
      numTechnicianPrice = parseFloat(technicianPrice);
      if (isNaN(numTechnicianPrice) || numTechnicianPrice < 0) {
        setFormError("Technician Price must be a valid non-negative number.");
        return;
      }
    }

    let numRetailPrice: number | null = null;
    if (retailPrice && retailPrice.trim() !== "") {
      numRetailPrice = parseFloat(retailPrice);
      if (isNaN(numRetailPrice) || numRetailPrice < 0) {
        setFormError("Retail Price must be a valid non-negative number.");
        return;
      }
    }

    let numPurchasePrice: number | null = null;
    if (purchasePrice && purchasePrice.trim() !== "") {
      numPurchasePrice = parseFloat(purchasePrice);
      if (isNaN(numPurchasePrice) || numPurchasePrice < 0) {
        setFormError("Purchase Price must be a valid non-negative number.");
        return;
      }
    }

    setSubmitting(true);

    try {
      let finalImageUrl: string | null = null;

      // 1. Upload Image to Supabase Storage if selected
      if (selectedFile) {
        const uploadResult = await uploadProductImage(selectedFile);
        if (uploadResult.url) {
          finalImageUrl = uploadResult.url;
        } else if (uploadResult.error) {
          console.warn("Storage upload failed, proceeding without uploaded URL:", uploadResult.error);
        }
      }

      // 2. Prepare product record with category object and smart image fallback
      const numMinOrderQuantity = minOrderQuantity ? parseInt(minOrderQuantity, 10) : 1;
      const selectedCategoryObj = categories.find((c) => c.id === categoryId);

      // Auto-assign default Side Key placeholder if no image provided and category or name is side key
      if (!finalImageUrl) {
        const isSideKey =
          (selectedCategoryObj?.name && selectedCategoryObj.name.toLowerCase().includes("side")) ||
          name.toLowerCase().includes("side key") ||
          name.toLowerCase().includes("sidekey");
        if (isSideKey) {
          finalImageUrl = "/images/sidekey-placeholder.svg";
        }
      }

      const newProductRecord = {
        name: name.trim(),
        slug: slug.trim() || generateSlug(name),
        sku: sku.trim().toUpperCase(),
        category_id: categoryId || null,
        category: selectedCategoryObj
          ? { id: selectedCategoryObj.id, name: selectedCategoryObj.name, slug: selectedCategoryObj.slug }
          : null,
        price: numPrice,
        wholesale_price: numPrice,
        technician_price: numTechnicianPrice,
        retail_price: numRetailPrice,
        purchase_price: numPurchasePrice,
        min_order_quantity: numMinOrderQuantity > 0 ? numMinOrderQuantity : 1,
        stock_quantity: numStock,
        short_description: shortDescription.trim() || null,
        description: description.trim() || null,
        image_url: finalImageUrl,
        is_active: isActive,
        featured: isFeatured,
      };

      // 2. Save product through unified customProducts system (syncs Server API, Supabase, and localStorage)
      const saveResult = await saveProduct(newProductRecord);

      if (!saveResult.success && saveResult.error) {
        setFormError(saveResult.error);
        setSubmitting(false);
        return;
      }

      setSuccessToast(true);
      setTimeout(() => {
        router.push("/admin/products");
      }, 1000);
    } catch (err: unknown) {
      console.error("Submission failed:", err);
      const e = err as Error;
      setFormError(e.message || "An unexpected error occurred while saving the product.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12">
      {/* Toast */}
      {successToast && (
        <div className="fixed top-5 right-5 z-50 bg-emerald-700 text-white text-xs font-semibold px-4 py-3 rounded-xl shadow-xl flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4" />
          <span>Product created successfully! Redirecting to inventory...</span>
        </div>
      )}

      {/* Top Header & Breadcrumb */}
      <div className="flex items-center justify-between">
        <div>
          <Link
            href="/admin/products"
            className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-secondary mb-2 transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Products Inventory</span>
          </Link>
          <h1 className="text-2xl font-black text-primary tracking-tight flex items-center gap-2.5">
            <Package className="w-6 h-6 text-secondary" />
            <span>Add New Mobile Spare Part</span>
          </h1>
        </div>
      </div>

      {/* Error Alert */}
      {formError && (
        <div className="p-4 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700 flex items-start gap-2.5">
          <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
          <span>{formError}</span>
        </div>
      )}

      {/* Main Form */}
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Card 1: Core Product Information */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 pb-2 border-b border-slate-100">
            Basic Information
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
            {/* Name */}
            <div className="space-y-1 sm:col-span-2">
              <label className="font-bold text-charcoal block">
                Product Title / Part Name *
              </label>
              <input
                type="text"
                value={name}
                onChange={handleNameChange}
                placeholder="e.g. VIVO Y20 SUNLONG BLACK UNIT"
                required
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              />
            </div>

            {/* Slug */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal">URL Slug *</label>
                <button
                  type="button"
                  onClick={() => setSlugAutoGenerated(!slugAutoGenerated)}
                  className="text-[10px] text-secondary font-semibold hover:underline"
                >
                  {slugAutoGenerated ? "Manual Edit" : "Auto-Generate"}
                </button>
              </div>
              <input
                type="text"
                value={slug}
                onChange={(e) => {
                  setSlugAutoGenerated(false);
                  setSlug(e.target.value);
                }}
                placeholder="vivo-y20-sunlong-black-unit"
                required
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface font-mono text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              />
            </div>

            {/* SKU */}
            <div className="space-y-1">
              <label className="font-bold text-charcoal block">SKU / Part Code *</label>
              <input
                type="text"
                value={sku}
                onChange={(e) => setSku(e.target.value.toUpperCase())}
                placeholder="ZB-LCD-V20S"
                required
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface font-mono text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs uppercase"
              />
            </div>

            {/* Category Dropdown */}
            <div className="space-y-1">
              <label className="font-bold text-charcoal block">Category *</label>
              <select
                value={categoryId}
                onChange={(e) => setCategoryId(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              >
                {loadingCategories ? (
                  <option>Loading categories...</option>
                ) : (
                  categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))
                )}
              </select>
            </div>

            {/* Wholesale Selling Price (PKR) */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal block">
                  Wholesale Selling Price (PKR) *
                </label>
                <span className="text-[10px] font-bold text-slate-700 bg-slate-100 px-1.5 py-0.5 rounded">
                  بیس ہول سیل ریٹ
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3.5 top-2.5 text-slate-400 font-bold">
                  Rs.
                </span>
                <input
                  type="number"
                  min="0"
                  step="any"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  placeholder="e.g. 50, 100, 99.50, 250.75"
                  required
                  className="w-full pl-11 pr-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs font-bold"
                />
              </div>
            </div>

            {/* Technician Selling Price (PKR) */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal">
                  Technician Price (PKR)
                </label>
                <span className="text-[10px] font-bold text-amber-700 bg-amber-50 px-1.5 py-0.5 rounded border border-amber-200">
                  ٹیکنیشن ریٹ • Manual
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3.5 top-2.5 text-slate-400 font-bold">
                  Rs.
                </span>
                <input
                  type="number"
                  min="0"
                  step="any"
                  value={technicianPrice}
                  onChange={(e) => setTechnicianPrice(e.target.value)}
                  placeholder="Manual price (e.g. 100, 99.50, 250.75)"
                  className="w-full pl-11 pr-3.5 py-2.5 rounded-lg border border-amber-300 bg-amber-50/20 text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-amber-500 text-xs font-bold"
                />
              </div>
            </div>

            {/* Retail Selling Price (PKR) */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal">
                  Retail Price (PKR)
                </label>
                <span className="text-[10px] font-bold text-blue-700 bg-blue-50 px-1.5 py-0.5 rounded border border-blue-200">
                  پرچون ریٹ • Manual
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3.5 top-2.5 text-slate-400 font-bold">
                  Rs.
                </span>
                <input
                  type="number"
                  min="0"
                  step="any"
                  value={retailPrice}
                  onChange={(e) => setRetailPrice(e.target.value)}
                  placeholder="Manual price (e.g. 100, 99.50, 250.75)"
                  className="w-full pl-11 pr-3.5 py-2.5 rounded-lg border border-blue-200 bg-blue-50/20 text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 text-xs font-bold"
                />
              </div>
            </div>

            {/* Purchase Price (PKR) - Admin Only */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal">
                  Purchase Price / Cost (PKR)
                </label>
                <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded border border-emerald-200">
                  خریداری ریٹ • Admin Only
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3.5 top-2.5 text-slate-400 font-bold">
                  Rs.
                </span>
                <input
                  type="number"
                  min="0"
                  step="any"
                  value={purchasePrice}
                  onChange={(e) => setPurchasePrice(e.target.value)}
                  placeholder="Manual price (e.g. 50, 49.50, 180.25)"
                  className="w-full pl-11 pr-3.5 py-2.5 rounded-lg border border-emerald-300 bg-emerald-50/20 text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500 text-xs font-bold"
                />
              </div>
            </div>

            {/* Live Profit Preview Banner */}
            {price && purchasePrice && (
              <div className="sm:col-span-2 p-3 bg-emerald-50 border border-emerald-200 rounded-xl flex flex-wrap items-center justify-between gap-2 text-xs">
                <div className="flex items-center gap-2">
                  <span className="text-base">💰</span>
                  <div>
                    <span className="text-slate-600 font-medium">Estimated Net Profit per Unit: </span>
                    <strong className={`font-mono text-sm ${parseFloat(price) - parseFloat(purchasePrice) >= 0 ? "text-emerald-700" : "text-rose-600"}`}>
                      {parseFloat(price) - parseFloat(purchasePrice) >= 0 ? "+" : ""}
                      Rs. {(parseFloat(price) - parseFloat(purchasePrice)).toLocaleString("en-PK")}
                    </strong>
                  </div>
                </div>
                {parseFloat(price) > 0 && (
                  <span className="font-mono font-bold text-emerald-800 bg-emerald-200/70 px-2 py-0.5 rounded text-[11px]">
                    Margin: {(((parseFloat(price) - parseFloat(purchasePrice)) / parseFloat(price)) * 100).toFixed(1)}%
                  </span>
                )}
              </div>
            )}

            {/* Stock Quantity */}
            <div className="space-y-1">
              <label className="font-bold text-charcoal block">Stock Quantity *</label>
              <input
                type="number"
                min="0"
                value={stockQuantity}
                onChange={(e) => setStockQuantity(e.target.value)}
                placeholder="25"
                required
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              />
            </div>

            {/* Minimum Order Quantity (MOQ) */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="font-bold text-charcoal block">
                  Minimum Order Quantity (MOQ) *
                </label>
                <span className="text-[10px] font-bold text-amber-800 bg-amber-50 px-1.5 py-0.5 rounded border border-amber-200">
                  کم از کم تعداد
                </span>
              </div>
              <input
                type="number"
                min="1"
                step="1"
                value={minOrderQuantity}
                onChange={(e) => setMinOrderQuantity(e.target.value)}
                placeholder="1"
                required
                className="w-full px-3.5 py-2.5 rounded-lg border border-amber-300 bg-amber-50/20 text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-amber-500 text-xs font-bold"
              />
              <p className="text-[10px] text-slate-400">
                User is se kam quantity cart me add nahi kar sakega (Default: 1).
              </p>
            </div>
          </div>
        </div>

        {/* Card 2: Image Upload (Supabase Storage) */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
          <div className="flex items-center justify-between pb-2 border-b border-slate-100">
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
              Product Image (Supabase Storage: &apos;product-images&apos;)
            </h2>
            <span className="text-[11px] text-slate-400 font-medium">Max 5MB (JPG, PNG, WEBP)</span>
          </div>

          <div className="space-y-4">
            {imagePreview ? (
              /* Preview Area */
              <div className="flex items-center gap-5 p-4 border border-slate-200 rounded-xl bg-slate-50">
                <div className="w-24 h-24 sm:w-28 sm:h-28 aspect-square bg-white rounded-lg border border-slate-200 p-2 overflow-hidden flex items-center justify-center shrink-0 shadow-2xs">
                  <img
                    src={imagePreview}
                    alt="Preview"
                    className="w-full h-full object-contain"
                  />
                </div>
                <div className="space-y-1.5 min-w-0 flex-1">
                  <p className="text-xs font-bold text-primary truncate">
                    {selectedFile?.name || "Selected Image"}
                  </p>
                  <p className="text-[11px] text-slate-400">
                    {selectedFile ? `${(selectedFile.size / 1024).toFixed(1)} KB` : "Ready to upload"}
                  </p>
                  <button
                    type="button"
                    onClick={handleRemoveImage}
                    className="inline-flex items-center gap-1 text-xs text-rose-600 hover:text-rose-700 font-semibold pt-1"
                  >
                    <X className="w-3.5 h-3.5" />
                    <span>Remove / Replace image</span>
                  </button>
                </div>
              </div>
            ) : (
              /* Upload Drag & Drop Area */
              <label className="border-2 border-dashed border-slate-300 hover:border-secondary/60 rounded-xl p-8 flex flex-col items-center justify-center text-center cursor-pointer transition-colors bg-slate-50/50 hover:bg-slate-50">
                <div className="w-12 h-12 rounded-full bg-secondary/10 text-secondary flex items-center justify-center mb-3">
                  <UploadCloud className="w-6 h-6" />
                </div>
                <span className="text-xs font-bold text-primary">
                  Click to upload product image or drag & drop
                </span>
                <span className="text-[11px] text-slate-400 mt-1">
                  PNG, JPG, or WEBP up to 5MB (Stored in Supabase Storage)
                </span>
                <input
                  type="file"
                  accept="image/jpeg,image/png,image/webp,image/jpg"
                  onChange={handleFileSelect}
                  className="hidden"
                />
              </label>
            )}
          </div>
        </div>

        {/* Card 3: Descriptions & Toggles */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 pb-2 border-b border-slate-100">
            Description & Store Visibility
          </h2>

          <div className="space-y-4 text-xs">
            {/* Short Description */}
            <div className="space-y-1">
              <label className="font-bold text-charcoal block">Short Description</label>
              <input
                type="text"
                value={shortDescription}
                onChange={(e) => setShortDescription(e.target.value)}
                placeholder="High-clarity original IC tested display assembly."
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              />
            </div>

            {/* Detailed Description */}
            <div className="space-y-1">
              <label className="font-bold text-charcoal block">Detailed Technical Description</label>
              <textarea
                rows={3}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Detailed compatibility, touch response, flex ribbon quality, testing notes..."
                className="w-full px-3.5 py-2.5 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary text-xs"
              />
            </div>

            {/* Checkbox Toggles */}
            <div className="pt-2 flex flex-col sm:flex-row gap-6 border-t border-slate-100">
              <label className="flex items-center gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isActive}
                  onChange={(e) => setIsActive(e.target.checked)}
                  className="w-4 h-4 text-secondary rounded border-slate-300 focus:ring-secondary"
                />
                <span className="font-bold text-charcoal">Active on Storefront</span>
              </label>

              <label className="flex items-center gap-2.5 cursor-pointer">
                <input
                  type="checkbox"
                  checked={isFeatured}
                  onChange={(e) => setIsFeatured(e.target.checked)}
                  className="w-4 h-4 text-secondary rounded border-slate-300 focus:ring-secondary"
                />
                <span className="font-bold text-charcoal flex items-center gap-1">
                  <Sparkles className="w-3.5 h-3.5 text-secondary" />
                  Featured Part
                </span>
              </label>
            </div>
          </div>
        </div>

        {/* Submit Actions */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <Link
            href="/admin/products"
            className="px-5 py-2.5 rounded-xl text-xs font-semibold text-slate-500 hover:bg-slate-200 transition-colors"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={submitting}
            className="px-6 py-2.5 rounded-xl bg-secondary hover:bg-secondary-hover text-white text-xs font-bold shadow-sm transition-all disabled:opacity-60 flex items-center gap-2"
          >
            {submitting ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                <span>Uploading & Saving Part...</span>
              </>
            ) : (
              <span>Save & Publish Product</span>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
