"use client";

import React, { useState, useEffect } from "react";
import {
  Layers,
  Plus,
  Search,
  Trash2,
  Edit2,
  AlertTriangle,
  X,
  CheckCircle2,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import { Category } from "@/lib/types";
import { supabase } from "@/lib/supabase";

// Fallback initial categories for immediate preview
const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "LCD & Touch Units",
    slug: "lcd-units",
    description: "Complete LCD touch screen assemblies and black units",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Charging Flex & Boards",
    slug: "charging-flex",
    description: "Sub-boards, charging ribbons, and mic modules",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "OCA Glass & Touch",
    slug: "oca-glass",
    description: "Front glass, OCA lenses, and touch digitizers",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Batteries & Housings",
    slug: "batteries-housings",
    description: "Original replacement batteries and phone frames",
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    name: "Repair Tools & Supplies",
    slug: "repair-tools",
    description: "Heatguns, soldering stations, board grippers, jumper wires",
    created_at: new Date().toISOString(),
  },
];

export default function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  // Modal State (Add or Edit)
  const [modalOpen, setModalOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<Category | null>(null);
  const [formName, setFormName] = useState("");
  const [formSlug, setFormSlug] = useState("");
  const [formDescription, setFormDescription] = useState("");
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [formLoading, setFormLoading] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  // Delete Confirmation State
  const [deleteTarget, setDeleteTarget] = useState<Category | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);

  // Toast feedback
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Fetch Categories
  const fetchCategories = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from("categories")
        .select("*")
        .order("name", { ascending: true });

      if (data && data.length > 0) {
        setCategories(data);
        if (typeof window !== "undefined") {
          localStorage.setItem("zubair_mobile_categories", JSON.stringify(data));
        }
      } else {
        const local = typeof window !== "undefined" ? localStorage.getItem("zubair_mobile_categories") : null;
        if (local) {
          try {
            setCategories(JSON.parse(local));
          } catch {
            setCategories(INITIAL_CATEGORIES);
          }
        } else {
          setCategories(INITIAL_CATEGORIES);
        }
      }
    } catch (err) {
      console.warn("Could not fetch categories from Supabase, using local list:", err);
      const local = typeof window !== "undefined" ? localStorage.getItem("zubair_mobile_categories") : null;
      if (local) {
        try {
          setCategories(JSON.parse(local));
        } catch {
          setCategories(INITIAL_CATEGORIES);
        }
      } else {
        setCategories(INITIAL_CATEGORIES);
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCategories();
  }, []);

  // Slug auto-generator
  const generateSlug = (text: string) => {
    return text
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  };

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setFormName(val);
    if (slugAutoGenerated && !editingCategory) {
      setFormSlug(generateSlug(val));
    }
  };

  const openAddModal = () => {
    setEditingCategory(null);
    setFormName("");
    setFormSlug("");
    setFormDescription("");
    setSlugAutoGenerated(true);
    setFormError(null);
    setModalOpen(true);
  };

  const openEditModal = (cat: Category) => {
    setEditingCategory(cat);
    setFormName(cat.name);
    setFormSlug(cat.slug);
    setFormDescription(cat.description || "");
    setSlugAutoGenerated(false);
    setFormError(null);
    setModalOpen(true);
  };

  const handleFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formName.trim() || !formSlug.trim()) {
      setFormError("Name and Slug are required.");
      return;
    }

    setFormLoading(true);

    try {
      if (editingCategory) {
        // Update
        const { error } = await supabase
          .from("categories")
          .update({
            name: formName.trim(),
            slug: formSlug.trim(),
            description: formDescription.trim() || null,
          })
          .eq("id", editingCategory.id);

        const updated = categories.map((c) =>
          c.id === editingCategory.id
            ? {
                ...c,
                name: formName.trim(),
                slug: formSlug.trim(),
                description: formDescription.trim(),
              }
            : c
        );
        setCategories(updated);
        if (typeof window !== "undefined") {
          localStorage.setItem("zubair_mobile_categories", JSON.stringify(updated));
        }
        showToast(`Category "${formName.trim()}" updated successfully.`);
      } else {
        // Create
        const newCat: Partial<Category> = {
          name: formName.trim(),
          slug: formSlug.trim(),
          description: formDescription.trim() || null,
        };

        const { data, error } = await supabase
          .from("categories")
          .insert([newCat])
          .select()
          .single();

        let updated: Category[];
        if (!error && data) {
          updated = [...categories, data];
        } else {
          console.warn("Supabase insert notice, saving locally:", error);
          const localNew: Category = {
            id: `cat-${Date.now()}`,
            name: formName.trim(),
            slug: formSlug.trim(),
            description: formDescription.trim() || null,
            created_at: new Date().toISOString(),
          };
          updated = [...categories, localNew];
        }

        setCategories(updated);
        if (typeof window !== "undefined") {
          localStorage.setItem("zubair_mobile_categories", JSON.stringify(updated));
        }
        showToast(`New category "${formName.trim()}" created successfully.`);
      }

      setModalOpen(false);
    } catch (err: unknown) {
      console.error("Form error:", err);
      setFormError("Failed to save category. Please check slug uniqueness.");
    } finally {
      setFormLoading(false);
    }
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;

    setDeleteLoading(true);
    setDeleteError(null);

    try {
      // Check if products reference this category
      const { data: prodCount, error: prodErr } = await supabase
        .from("products")
        .select("id")
        .eq("category_id", deleteTarget.id);

      if (prodCount && prodCount.length > 0) {
        setDeleteError(
          `Cannot delete "${deleteTarget.name}". There are ${prodCount.length} active products linked to it. Reassign or delete those products first.`
        );
        setDeleteLoading(false);
        return;
      }

      // Delete from Supabase
      const { error } = await supabase
        .from("categories")
        .delete()
        .eq("id", deleteTarget.id);

      if (error) {
        if (error.code === "23503" || error.message.includes("foreign key")) {
          setDeleteError(
            `Cannot delete category due to linked products in database. Reassign them first.`
          );
          setDeleteLoading(false);
          return;
        }
      }

      // Remove from state
      const updated = categories.filter((c) => c.id !== deleteTarget.id);
      setCategories(updated);
      if (typeof window !== "undefined") {
        localStorage.setItem("zubair_mobile_categories", JSON.stringify(updated));
      }
      showToast(`Category "${deleteTarget.name}" deleted.`);
      setDeleteTarget(null);
    } catch (err: unknown) {
      console.error("Delete error:", err);
      setDeleteError("Failed to delete category. Check if products are assigned to it.");
    } finally {
      setDeleteLoading(false);
    }
  };

  const filteredCategories = categories.filter((c) => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return true;
    return (
      c.name.toLowerCase().includes(q) ||
      c.slug.toLowerCase().includes(q) ||
      (c.description && c.description.toLowerCase().includes(q))
    );
  });

  return (
    <div className="space-y-6">
      {/* Toast Banner */}
      {toastMessage && (
        <div className="fixed top-5 right-5 z-50 bg-emerald-700 text-white text-xs font-semibold px-4 py-3 rounded-xl shadow-xl flex items-center gap-2 animate-fade-in">
          <CheckCircle2 className="w-4 h-4" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-primary tracking-tight flex items-center gap-2.5">
            <Layers className="w-6 h-6 text-secondary" />
            <span>Category Management</span>
          </h1>
          <p className="text-xs text-slate-500 mt-1">
            Organize mobile spare parts into browsable categories and manage slugs.
          </p>
        </div>

        <button
          type="button"
          onClick={openAddModal}
          className="inline-flex items-center gap-2 bg-secondary hover:bg-secondary-hover text-white px-4 py-2.5 rounded-xl font-bold text-xs shadow-sm transition-all hover:shadow"
        >
          <Plus className="w-4 h-4" />
          <span>Add New Category</span>
        </button>
      </div>

      {/* Search & Stats Bar */}
      <div className="bg-white rounded-2xl border border-slate-200 p-4 shadow-2xs flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="relative w-full sm:max-w-md">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search categories by name, slug or description..."
            className="w-full pl-9 pr-4 py-2 rounded-xl border border-slate-200 bg-surface text-xs text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary"
          />
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
        </div>

        <div className="flex items-center gap-3 text-xs text-slate-500 w-full sm:w-auto justify-between sm:justify-end">
          <span>
            Total: <strong className="text-primary font-bold">{categories.length}</strong> Categories
          </span>
          <button
            onClick={fetchCategories}
            className="p-1.5 rounded-lg text-slate-400 hover:text-secondary hover:bg-slate-50"
            title="Refresh list"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Categories Data Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">
        {loading ? (
          <div className="p-12 text-center">
            <div className="w-8 h-8 border-3 border-secondary border-t-transparent rounded-full animate-spin mx-auto mb-3" />
            <p className="text-xs text-slate-500">Loading categories from database...</p>
          </div>
        ) : filteredCategories.length === 0 ? (
          <div className="p-12 text-center space-y-2">
            <Layers className="w-10 h-10 text-slate-300 mx-auto" />
            <p className="text-sm font-bold text-primary">No Categories Found</p>
            <p className="text-xs text-slate-400">
              No categories match &ldquo;{searchQuery}&rdquo;.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 bg-surface text-slate-500 font-bold uppercase tracking-wider text-[11px]">
                  <th className="py-3.5 px-4 sm:px-6">Category Name</th>
                  <th className="py-3.5 px-4">Slug</th>
                  <th className="py-3.5 px-4">Description</th>
                  <th className="py-3.5 px-4">Created Date</th>
                  <th className="py-3.5 px-4 sm:px-6 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredCategories.map((cat) => (
                  <tr key={cat.id} className="hover:bg-slate-50/70 transition-colors">
                    <td className="py-3.5 px-4 sm:px-6">
                      <div className="font-bold text-primary text-xs sm:text-sm">
                        {cat.name}
                      </div>
                    </td>
                    <td className="py-3.5 px-4">
                      <span className="font-mono text-[11px] bg-slate-100 text-slate-700 px-2 py-0.5 rounded">
                        {cat.slug}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-500 max-w-xs truncate">
                      {cat.description || <span className="text-slate-300 italic">None</span>}
                    </td>
                    <td className="py-3.5 px-4 text-slate-400">
                      {cat.created_at
                        ? new Date(cat.created_at).toLocaleDateString()
                        : "Initial"}
                    </td>
                    <td className="py-3.5 px-4 sm:px-6 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          type="button"
                          onClick={() => openEditModal(cat)}
                          className="p-1.5 rounded-lg text-slate-400 hover:text-secondary hover:bg-slate-100 transition-colors"
                          title="Edit category"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          type="button"
                          onClick={() => {
                            setDeleteTarget(cat);
                            setDeleteError(null);
                          }}
                          className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition-colors"
                          title="Delete category"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Add / Edit Category Modal */}
      {modalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="fixed inset-0 bg-primary/60 backdrop-blur-xs"
            onClick={() => setModalOpen(false)}
          />
          <div className="relative bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-md w-full p-6 space-y-5 z-10">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h2 className="text-base font-black text-primary">
                {editingCategory ? "Edit Category" : "Add New Category"}
              </h2>
              <button
                onClick={() => setModalOpen(false)}
                className="p-1 text-slate-400 hover:text-charcoal rounded-lg"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {formError && (
              <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700">
                {formError}
              </div>
            )}

            <form onSubmit={handleFormSubmit} className="space-y-4 text-xs">
              {/* Category Name */}
              <div className="space-y-1">
                <label className="font-bold text-charcoal">Category Name *</label>
                <input
                  type="text"
                  value={formName}
                  onChange={handleNameChange}
                  placeholder="e.g. Charging Flex & Boards"
                  required
                  className="w-full px-3.5 py-2 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary"
                />
              </div>

              {/* Slug */}
              <div className="space-y-1">
                <div className="flex items-center justify-between">
                  <label className="font-bold text-charcoal">URL Slug *</label>
                  {!editingCategory && (
                    <button
                      type="button"
                      onClick={() => setSlugAutoGenerated(!slugAutoGenerated)}
                      className="text-[10px] text-secondary font-semibold hover:underline"
                    >
                      {slugAutoGenerated ? "Manual Edit" : "Auto-Generate"}
                    </button>
                  )}
                </div>
                <input
                  type="text"
                  value={formSlug}
                  onChange={(e) => {
                    setSlugAutoGenerated(false);
                    setFormSlug(e.target.value);
                  }}
                  placeholder="charging-flex"
                  required
                  className="w-full px-3.5 py-2 rounded-lg border border-slate-200 bg-surface font-mono text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary"
                />
              </div>

              {/* Description */}
              <div className="space-y-1">
                <label className="font-semibold text-slate-500">Description</label>
                <textarea
                  rows={3}
                  value={formDescription}
                  onChange={(e) => setFormDescription(e.target.value)}
                  placeholder="Short summary of items in this category..."
                  className="w-full px-3.5 py-2 rounded-lg border border-slate-200 bg-surface text-charcoal focus:bg-white focus:outline-none focus:ring-2 focus:ring-secondary"
                />
              </div>

              {/* Buttons */}
              <div className="pt-2 flex items-center justify-end gap-2.5">
                <button
                  type="button"
                  onClick={() => setModalOpen(false)}
                  className="px-4 py-2 rounded-xl text-slate-500 hover:bg-slate-100 font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={formLoading}
                  className="px-5 py-2 rounded-xl bg-secondary hover:bg-secondary-hover text-white font-bold shadow-xs disabled:opacity-60"
                >
                  {formLoading ? "Saving..." : editingCategory ? "Update Category" : "Create Category"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="fixed inset-0 bg-primary/60 backdrop-blur-xs"
            onClick={() => setDeleteTarget(null)}
          />
          <div className="relative bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-sm w-full p-6 space-y-4 z-10 text-center">
            <div className="w-12 h-12 rounded-full bg-rose-100 text-rose-600 flex items-center justify-center mx-auto">
              <AlertTriangle className="w-6 h-6" />
            </div>

            <div className="space-y-1">
              <h3 className="text-base font-black text-primary">Confirm Deletion</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Are you sure you want to delete{" "}
                <strong className="text-charcoal">&ldquo;{deleteTarget.name}&rdquo;</strong>?
                This action cannot be undone.
              </p>
            </div>

            {deleteError && (
              <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700 text-left">
                {deleteError}
              </div>
            )}

            <div className="pt-2 flex items-center justify-center gap-3">
              <button
                type="button"
                onClick={() => setDeleteTarget(null)}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 hover:bg-slate-100"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={confirmDelete}
                disabled={deleteLoading}
                className="px-5 py-2 rounded-xl text-xs font-bold bg-rose-600 hover:bg-rose-700 text-white shadow-sm disabled:opacity-60"
              >
                {deleteLoading ? "Deleting..." : "Yes, Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
